---
title: "Individual differences experiment"
output:
  html_document:
    df_print: paged
---

```{r init, echo=F}


library(lme4)
library(lmerTest)
library(tidyverse)
library(effectsize)

theme_set(theme_bw())


#myNorm = function(x) {
#  return(x * 2 / (max(x) - min(x)))
#}

myNorm = function(x) {
 xmin = min(x, na.rm = TRUE)
 xmax = max(x, na.rm = TRUE) 
 x_scaled = (x - xmin)/(xmax - xmin) * 2 -1
 return(x_scaled)
}



```

```{r load_data, echo=F, fig.width=10, fig.height=2}



d.adaptation = read.csv("../data/5_adaptation_data-merged.csv")
d.ktt = read.csv("../data/1_scores_ktt-anon.csv") %>% 
  #dplyr::filter(is.na(exclude) | exclude != 1) %>%
  dplyr::mutate(score = case_when(is.na(exclude) | exclude != 1 ~ score)) %>%
  dplyr::select(workerid, score) %>% 
  dplyr::rename (ktt.score = score) 
d.rmet = read.csv("../data/2_scores_rmet-anon.csv") %>%
  #dplyr::filter(is.na(exclude) | exclude != 1) %>%
  dplyr::mutate(score = case_when(is.na(exclude) | exclude != 1 ~ score)) %>%
  dplyr::select("workerid", "score") %>% 
  dplyr::rename (rmet.score = score)
d.crt = read.csv("../data/3_crt_scores-anon.csv") %>%
  #dplyr::filter(is.na(exclude) | exclude != 1) %>%
  dplyr::mutate(crt = case_when(is.na(exclude) | exclude != 1 ~ crt)) %>%
  dplyr::select("workerid", "crt") %>% 
  dplyr::rename(crt.score = crt)

d.art = read.csv("../data/4_art_scores_with_timeouts_false_pos-anon.csv") %>%
  #dplyr::filter(is.na(exclude) | exclude != 1) %>%
  dplyr::mutate(art.score = case_when(is.na(exclude) | exclude != 1 ~ art.score)) %>%
  dplyr::select("workerid", "art.score") 

d.ktt.all = read.csv("../data/1_scores_ktt-anon.csv") %>%
  dplyr::select(workerid, score)

print(paste("Number of participants before ID test exclusions:", length(unique(d.ktt.all$workerid))))

d.adapter_types = d.adaptation %>% 
  merge(., d.ktt.all) %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::group_by(adapter) %>%
  dplyr::summarize(count = n()) %>%
  dplyr::mutate(freq = count / sum(count))

knitr::kable(d.adapter_types)

d = d.adaptation %>% 
  merge(., d.ktt) %>% 
  merge(., d.rmet) %>% 
  merge(., d.crt) %>% 
  merge(., d.art) 
# remove one outlier
#%>% dplyr::filter(ktt.score > 15)

d.adapter_types = d %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::group_by(adapter) %>%
  dplyr::summarize(count = n()) %>%
  dplyr::mutate(freq = count / sum(count))

print(paste("Number of participants after ID test exclusions:", length(unique(d$workerid))))
write.csv(unique(d$workerid), file="../data/A_included_participants.csv")
knitr::kable(d.adapter_types)

d.diff = d %>% 
  dplyr::filter(condition == "cautious") %>%
  dplyr::rename(likelihood_ratio.cautious = likelihood_ratio) %>%
  dplyr::select(workerid, ktt.score, rmet.score, crt.score, art.score, likelihood_ratio.cautious) %>%
  merge(d %>% 
          dplyr::filter(condition == "confident") %>%
          dplyr::rename(likelihood_ratio.confident = likelihood_ratio) %>%
          dplyr::select(workerid, likelihood_ratio.confident)) %>%
  mutate(likelihood_diff = likelihood_ratio.confident - likelihood_ratio.cautious)

d = d %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::select(workerid, adapter) %>%
  merge(d, .)

d.long = d %>% 
  pivot_longer(tidyselect::ends_with(".score"), 
               names_to = "measure", 
               values_to = "score")

d.long %>% 
  ggplot(aes(x=score, fill=1)) + 
    geom_density() + 
    theme(legend.position = "none") + 
    facet_wrap(~measure, ncol = 4, scales = "free")

d.long %>% 
  ggplot(aes(x=score, fill=adapter)) + 
    geom_density(alpha=0.5) + 
    theme(legend.position = "none") + 
    facet_wrap(~measure, ncol = 4, scales = "free")





d = d %>% dplyr::mutate(condition = factor(condition),
                 test_order = factor(test_order),
                 first_speaker_type = factor(first_speaker_type))
contrasts(d$condition) = contr.sum(2)
colnames(contrasts(d$condition)) = c("cautious")
contrasts(d$test_order) = contr.sum(2)
colnames(contrasts(d$test_order)) = c("parallel")
contrasts(d$first_speaker_type) = contr.sum(2)
colnames(contrasts(d$first_speaker_type)) = c("cautious")

model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               (1| workerid), 
             data = d)

print(summary(model))

d$art.score = myCenter(myNorm(d$art.score))

model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               art.score * condition +
               (1| workerid), 
             data = d, na.action = na.omit)

print(summary(model))

d$ktt.score = myCenter(myNorm(d$ktt.score))


model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               ktt.score * condition +
               (1| workerid), 
             data = d)

print(summary(model))

d$rmet.score = myCenter(myNorm(d$rmet.score))

model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               rmet.score * condition +
               (1| workerid), 
             data = d)

print(summary(model))

d$crt.score = myCenter(myNorm(d$crt.score))


model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               crt.score * condition +
               (1| workerid), 
             data = d)

print(summary(model))

model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               art.score * condition +
               ktt.score * condition +
               rmet.score * condition +
               crt.score * condition +
               (1| workerid), 
             data = na.omit(d))

print(summary(model), correlation=TRUE)

```



*Note*: Correlation is also stable if one excludes the person who scored 15 on the RTT task.

```{r corr_plots, echo=F, fig.width=4, fig.height=4}

d.diff %>%
 ggplot(aes(x=ktt.score, y=likelihood_diff)) + 
  geom_smooth(method="lm") + 
  geom_point() + 
  geom_point(col = "red", pch=3, 
             data = d.diff %>% 
               dplyr::group_by(ktt.score) %>% 
               dplyr::summarize(likelihood_diff = mean(likelihood_diff))) +
  ggtitle("KTT")

d.diff %>%
 ggplot(aes(x=art.score, y=likelihood_diff)) + 
  geom_smooth(method="lm") + 
  geom_point() + 
  geom_point(col = "red", pch=3, 
             data = d.diff %>% 
               dplyr::group_by(art.score) %>% 
               dplyr::summarize(likelihood_diff = mean(likelihood_diff))) +
  ggtitle("ART")


d.diff %>%
 ggplot(aes(x=crt.score, y=likelihood_diff)) + 
  geom_smooth(method="lm") + 
  geom_point() + 
  geom_point(col = "red", pch=3, 
             data = d.diff %>% 
               dplyr::group_by(crt.score) %>% 
               dplyr::summarize(likelihood_diff = mean(likelihood_diff))) +
  ggtitle("CRT")

d.diff %>%
 ggplot(aes(x=rmet.score, y=likelihood_diff)) + 
  geom_smooth(method="lm") + 
  geom_point() + 
  geom_point(col = "red", pch=3, 
             data = d.diff %>% 
               dplyr::group_by(rmet.score) %>% 
               dplyr::summarize(likelihood_diff = mean(likelihood_diff))) +
  ggtitle("RMET")


```


# Backward elimination

```{r backward_elimination, echo=F}

step_res = lmerTest::step(model)
final = lmerTest::get_model(step_res)

print(summary(final))


```


# Re-run of analysis just with KTT data

```{r ktt_only, echo=F, fig.width=4, fig.height=4}

d = d.adaptation %>% 
  merge(., d.ktt)

d.adapter_types = d %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::group_by(adapter) %>%
  dplyr::summarize(count = n()) %>%
  dplyr::mutate(freq = count / sum(count))

print(paste("Number of participants after ID test exclusions:", length(unique(d$workerid))))
knitr::kable(d.adapter_types)

d = d %>% dplyr::mutate(condition = factor(condition),
                 test_order = factor(test_order),
                 first_speaker_type = factor(first_speaker_type))
contrasts(d$condition) = contr.sum(2)
colnames(contrasts(d$condition)) = c("cautious")
contrasts(d$test_order) = contr.sum(2)
colnames(contrasts(d$test_order)) = c("parallel")
contrasts(d$first_speaker_type) = contr.sum(2)
colnames(contrasts(d$first_speaker_type)) = c("cautious")


d.diff = d %>% 
  dplyr::filter(condition == "cautious") %>%
  dplyr::rename(likelihood_ratio.cautious = likelihood_ratio) %>%
  dplyr::select(workerid, ktt.score, likelihood_ratio.cautious) %>%
  merge(d %>% 
          dplyr::filter(condition == "confident") %>%
          dplyr::rename(likelihood_ratio.confident = likelihood_ratio) %>%
          dplyr::select(workerid, likelihood_ratio.confident)) %>%
  mutate(likelihood_diff = likelihood_ratio.confident - likelihood_ratio.cautious)



d$ktt.score = myCenter(myNorm(d$ktt.score))
#d$likelihood_ratio = myCenter(myNorm(d$likelihood_ratio))


model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               ktt.score * condition +
               (1| workerid), 
             data = d)
step_res = lmerTest::step(model)
final = lmerTest::get_model(step_res)

print(summary(final))

d.diff %>%
 ggplot(aes(x=ktt.score, y=likelihood_diff)) + 
  geom_smooth(method="lm") + 
  geom_point() + 
  geom_point(col = "red", pch=3, 
             data = d.diff %>% 
               dplyr::group_by(ktt.score) %>% 
               dplyr::summarize(likelihood_diff = mean(likelihood_diff))) +
  ggtitle("KTT")



```

```{r power_analysis, echo=F}
library(InteractionPoweR)

test_power<-power_interaction_r2(
  alpha = 0.05,             # alpha, for the power analysis
  N =seq(64,168,by=8),                  # sample size
  r.x1x2.y = -.35,           # interaction effect to test (correlation between x1*x2 and y)
  r.x1.y = -.20,              # correlation between x1 and y
  r.x2.y = .05,              # correlation between x2 and y
  r.x1.x2 = 0.000            # correlation between x1 and x2
)

```

# Re-run of analysis just with RMET data

```{r rmet_only, echo=F, fig.width=4, fig.height=4}

d = d.adaptation %>% 
  merge(., d.rmet)

d.adapter_types = d %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::group_by(adapter) %>%
  dplyr::summarize(count = n()) %>%
  dplyr::mutate(freq = count / sum(count))

print(paste("Number of participants after ID test exclusions:", length(unique(d$workerid))))
knitr::kable(d.adapter_types)

d = d %>% dplyr::mutate(condition = factor(condition),
                 test_order = factor(test_order),
                 first_speaker_type = factor(first_speaker_type))
contrasts(d$condition) = contr.sum(2)
colnames(contrasts(d$condition)) = c("cautious")
contrasts(d$test_order) = contr.sum(2)
colnames(contrasts(d$test_order)) = c("parallel")
contrasts(d$first_speaker_type) = contr.sum(2)
colnames(contrasts(d$first_speaker_type)) = c("cautious")


d.diff = d %>% 
  dplyr::filter(condition == "cautious") %>%
  dplyr::rename(likelihood_ratio.cautious = likelihood_ratio) %>%
  dplyr::select(workerid, rmet.score, likelihood_ratio.cautious) %>%
  merge(d %>% 
          dplyr::filter(condition == "confident") %>%
          dplyr::rename(likelihood_ratio.confident = likelihood_ratio) %>%
          dplyr::select(workerid, likelihood_ratio.confident)) %>%
  mutate(likelihood_diff = likelihood_ratio.confident - likelihood_ratio.cautious)



d$rmet.score = myCenter(myNorm(d$rmet.score))


model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               rmet.score * condition +
               (1| workerid), 
             data = d)
step_res = lmerTest::step(model)
final = lmerTest::get_model(step_res)

print(summary(final))

d.diff %>%
 ggplot(aes(x=rmet.score, y=likelihood_diff)) + 
  geom_smooth(method="lm") + 
  geom_point() + 
  geom_point(col = "red", pch=3, 
             data = d.diff %>% 
               dplyr::group_by(rmet.score) %>% 
               dplyr::summarize(likelihood_diff = mean(likelihood_diff))) +
  ggtitle("RMET")



```

# Re-run of analysis just with RMET + KTT data

```{r rmet_ktt, echo=F, fig.width=4, fig.height=4}

d = d.adaptation %>% 
  merge(., d.rmet) %>%
  merge(., d.ktt)

d.adapter_types = d %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::group_by(adapter) %>%
  dplyr::summarize(count = n()) %>%
  dplyr::mutate(freq = count / sum(count))

print(paste("Number of participants after ID test exclusions:", length(unique(d$workerid))))
knitr::kable(d.adapter_types)

d = d %>% dplyr::mutate(condition = factor(condition),
                 test_order = factor(test_order),
                 first_speaker_type = factor(first_speaker_type))
contrasts(d$condition) = contr.sum(2)
colnames(contrasts(d$condition)) = c("cautious")
contrasts(d$test_order) = contr.sum(2)
colnames(contrasts(d$test_order)) = c("parallel")
contrasts(d$first_speaker_type) = contr.sum(2)
colnames(contrasts(d$first_speaker_type)) = c("cautious")


d.diff = d %>% 
  dplyr::filter(condition == "cautious") %>%
  dplyr::rename(likelihood_ratio.cautious = likelihood_ratio) %>%
  dplyr::select(workerid, rmet.score, ktt.score, likelihood_ratio.cautious) %>%
  merge(d %>% 
          dplyr::filter(condition == "confident") %>%
          dplyr::rename(likelihood_ratio.confident = likelihood_ratio) %>%
          dplyr::select(workerid, likelihood_ratio.confident)) %>%
  mutate(likelihood_diff = likelihood_ratio.confident - likelihood_ratio.cautious)



d$rmet.score = myCenter(myNorm(d$rmet.score))
d$ktt.score = myCenter(myNorm(d$ktt.score))


model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               rmet.score * condition +
               ktt.score * condition +
               (1| workerid), 
             data = na.omit(d))
step_res = lmerTest::step(model)
final = lmerTest::get_model(step_res)

print(summary(final))

print(parameters::standardize_parameters(final))


model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               rmet.score * condition +
               ktt.score * condition +
               (1| workerid), 
             data = d)

print(summary(model))





```


