---
title: "Individual differences experiment"
output:
  html_document:
    df_print: paged
---

```{r init, echo=F}


library(lme4)
library(lmerTest)
library(tidyverse)
library(effectsize)

theme_set(theme_bw())


myNorm = function(x) {
 xmin = min(x)
 xmax = max(x) 
 x_scaled = (x - xmin)/(xmax - xmin) * 2 -1
 return(x_scaled)
}



```

```{r load_data, echo=F, fig.width=10, fig.height=2}



d.adaptation = read.csv("../data/adaptation_data-merged.csv")
d.ktt = read.csv("../data/scores_ktt-anon.csv") %>% 
  #dplyr::filter(is.na(exclude) | exclude != 1) %>%
  dplyr::select(workerid, score) %>% 
  dplyr::rename (ktt.score = score) %>%
  dplyr::filter(ktt.score > 19)

print(paste("Number of participants before ID test exclusions:", length(unique(d.adaptation$workerid))))

d.adapter_types = d.adaptation %>% 
  merge(., d.ktt) %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::group_by(adapter) %>%
  dplyr::summarize(count = n()) %>%
  dplyr::mutate(freq = count / sum(count))

knitr::kable(d.adapter_types)

d = d.adaptation %>% 
  merge(., d.ktt) 

d.adapter_types = d %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::group_by(adapter) %>%
  dplyr::summarize(count = n()) %>%
  dplyr::mutate(freq = count / sum(count))

print(paste("Number of participants after ID test exclusions:", length(unique(d$workerid))))
knitr::kable(d.adapter_types)

write.csv(unique(d$workerid), "../data/A_included_participants.csv")


d.diff = d %>% 
  dplyr::filter(condition == "cautious") %>%
  dplyr::rename(likelihood_ratio.cautious = likelihood_ratio) %>%
  dplyr::rename(most_likely_model.cautious = most_likely_model) %>%
  dplyr::select(workerid, ktt.score, likelihood_ratio.cautious, most_likely_model.cautious) %>%
  merge(d %>% 
          dplyr::filter(condition == "confident") %>%
          dplyr::rename(likelihood_ratio.confident = likelihood_ratio) %>%
          dplyr::rename(most_likely_model.confident = most_likely_model) %>% 
          dplyr::select(workerid, likelihood_ratio.confident, most_likely_model.confident)) %>%
  mutate(likelihood_diff = likelihood_ratio.confident - likelihood_ratio.cautious) %>%
  mutate(most_likely_model.cautious.correct = most_likely_model.cautious == "cautious") %>%
  mutate(most_likely_model.confident.correct = most_likely_model.confident == "confident") %>%
  mutate(adapter_type = case_when(
    most_likely_model.confident.correct & most_likely_model.cautious.correct ~ "adapted to both speakers",
    most_likely_model.confident.correct & !most_likely_model.cautious.correct ~ "always confident",
    !most_likely_model.confident.correct & most_likely_model.cautious.correct ~ "always cautious",
    TRUE ~ "adapted to wrong speakers"
  ))



corr_plot = d.diff %>% 
  mutate(adapter_type = factor(adapter_type, levels=c("adapted to wrong speakers", "always cautious", "always confident", "adapted to both speakers"))) %>%
  ggplot(aes(x=likelihood_diff, y=ktt.score)) + 
  geom_point(aes(col=adapter_type, pch=adapter_type), size=3) +
  geom_smooth(method="lm") +
  theme(legend.position = "bottom") + 
  xlab ("Difference in likelihood ratio across two test conditions\n(LLR confident - LLR cautious)") + 
  ylab("Keep track task score") +
  guides(pch=guide_legend(title="Adapter type"), col=guide_legend("Adapter type"))

ggsave(filename="exp2-ktt-LLD.pdf", plot=corr_plot, width=8, height=6)



d = d %>% 
  dplyr::mutate(aligned = (condition == most_likely_model)) %>%
  dplyr::group_by(workerid) %>%
  dplyr::summarize(adapter = (sum(aligned) == 2)) %>%
  dplyr::select(workerid, adapter) %>%
  merge(d, .)

d.long = d %>% 
  pivot_longer(tidyselect::ends_with(".score"), 
               names_to = "measure", 
               values_to = "score")

d.long %>% 
  ggplot(aes(x=score, fill=1)) + 
    geom_density() + 
    theme(legend.position = "none") + 
    facet_wrap(~measure, ncol = 4, scales = "free")

d.long %>% 
  ggplot(aes(x=score, fill=adapter)) + 
    geom_density(alpha=0.5) + 
    theme(legend.position = "none") + 
    facet_wrap(~measure, ncol = 4, scales = "free")





d = d %>% dplyr::mutate(condition = factor(condition),
                 test_order = factor(test_order),
                 first_speaker_type = factor(first_speaker_type))
contrasts(d$condition) = contr.sum(2)
colnames(contrasts(d$condition)) = c("cautious")
contrasts(d$test_order) = contr.sum(2)
colnames(contrasts(d$test_order)) = c("parallel")
contrasts(d$first_speaker_type) = contr.sum(2)
colnames(contrasts(d$first_speaker_type)) = c("cautious")

model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               (1| workerid), 
             data = d)

print(summary(model))



d$ktt.score = myCenter(myNorm(d$ktt.score))


model = lmer(formula= likelihood_ratio ~ condition + 
               test_order + 
               first_speaker_type + 
               prior_likelihood_ratio + 
               first_speaker_type * condition + 
               ktt.score * condition +
               (1| workerid), 
             data = d)

print(summary(model))






```




```{r corr_plots, echo=F, fig.width=4, fig.height=4}

d.diff %>%
 ggplot(aes(x=ktt.score, y=likelihood_diff)) + 
  geom_smooth(method="lm") + 
  geom_point() + 
  geom_point(col = "red", pch=3, 
             data = d.diff %>% 
               dplyr::group_by(ktt.score) %>% 
               dplyr::summarize(likelihood_diff = mean(likelihood_diff))) +
  ggtitle("KTT")






```


# Backward elimination

```{r backward_elimination, echo=F}

step_res = lmerTest::step(model)
final = lmerTest::get_model(step_res)

print(summary(final))


```




